version: 0.1
phases:
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image...."
      - "docker build -t docker-test-repo  ."
      - "docker tag docker-test-repo:latest 257290997232.dkr.ecr.us-east-1.amazonaws.com/docker-test-repo:latest"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push 257290997232.dkr.ecr.us-east-1.amazonaws.com/docker-test-repo:latest"
 

