--- 
phases:
  pre-build:
    commands:
      - echo Logging into ECR
      - $ (aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "echo systemctl start docker"
      - "docker build -t docker-test-repo  ."
      - "docker tag docker-test-repo:latest 257290997232.dkr.ecr.us-east-1.amazonaws.com/docker-test-repo:latest"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push 257290997232.dkr.ecr.us-east-1.amazonaws.com/docker-test-repo:latest"
      
version: 0.1

